<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');


class Register extends CI_Controller {

    public function __construct(){
        parent::__construct();
       $this->load->model('Common_model');
    }


    public function index() {
      // echo print_r($this->session->userdata());exit;
      $this->load->view('register');
    }
     public function Signup() {
      // echo print_r($this->session->userdata());exit;
    //   print_r($_POST['choice']);exit;
    // pre($_POST);exit;
    if($_POST){
        
        $data=$this->security->xss_clean($_POST);
         $check = $this->Common_model->check_user($data);
     //pre($check[0]);exit;
        if($check[0] !=''){
            $data['user']=$check[0];
             $this->load->view('user',$data);
        }
        else
        {
            if(ctype_digit($data['username'])){
                $phone = $data['username'];
                $email = "";
            }else{
                $phone = "";
                $email = $data['username'];
            }
            $pass =password_hash($data["password"], PASSWORD_BCRYPT);
            $max = $this->Common_model->getMaxUserId();
            $max =(int)substr($max,3);
            //print_r($max) ;exit;
            $text= "EDO".($max+1);
            $message = [
            'logid' => $text, // Automatically generated by the model
            'email' => $email,
            'phone' => $phone,
            'password' => $pass,
            'status' => 'deactive',
            'role' => 's',
            'joindate' => date('Y-m-d:h-m-s')
             ];
            $str = $this->Common_model->insert($message,'logme');

            if($str!=''){
               
                redirect(base_url() . 'authentication', 'refresh');
            }else{
               $temp="Try again";
             $this->session->set_flashdata($temp);
              redirect(base_url() . 'authentication', 'refresh');
            }
        }
    }
    }

   private function Message($code,$mob)
    {
      $text=$code;
      $mobile_number=$mob;
      $url = "http://bhashsms.com/api/sendmsg.php?user=FastHelps&pass=Fast123&sender=FSTHLP&phone=".$mobile_number."&text=".$text."&priority=ndnd&stype=normal";
      $payload = file_get_contents($url);
      if($payload != ""){
        return;
      }else{
        return;
      }
    }
}
